apiVersion: backstage.io/v1alpha1
kind: Component
dockerfile: Dockerfile
metadata:
  name: Scania
  annotations:
    github.com/project-slug: rashinir/Scania
spec:
  type: other
  lifecycle: unknown
  owner: RashinIranpoor
